controllers/resource.py
from flask import *
from ..models import db, get_enum, defn, get_defn, defn_parse, render_column, defn_parse_raw, defn_snippet, get_rel, get_rel_defn, get_enum_with_grouping, postproc
from flask_security import login_required, current_user
from datetime import datetime
from sqlalchemy.inspection import inspect

from ..linkage.epidoc import full_parse_on_inscription

resource = Blueprint('resource', __name__)


@resource.context_processor
def inject_resource_helpers():
    return {
        "defn_parse": defn_parse,
        "render_column": render_column,
        "defn_parse_raw": defn_parse_raw,
        "defn_snippet": defn_snippet,
        "get_enum_with_grouping": get_enum_with_grouping,
        "postproc": postproc
    }


@resource.route("/<name>")
def index(name):
    try:
        R = get_enum(name)
    except:
        abort(403)

    return render_template("resource/index.html",
                           name=name,
                           R=R,
                           defn=get_defn(name, scope="summary"))


@resource.route("/<name>/show/<id>", methods=["GET", "POST"])
def show(name, id):
    try:
        R = get_enum(name)
    except:
        abort(403)

    item = R.query.get_or_404(id)

    return render_template("resource/show.html",
                           name=name,
                           R=R,
                           item=item,
                           defn=get_defn(name, scope="display"))


@resource.route("/<name>/edit/<id>", methods=["GET", "POST"])
@login_required
def edit(name, id):
    try:
        R = get_enum(name)
    except:
        abort(403)

    item = R.query.get_or_404(id)
    defn = get_defn(name, scope="display")

    if request.method == "POST":
        item = apply_defn_post_data_to_obj(defn, item)

        db.session.commit()
        flash('Changes committed successfully.')
        return redirect(url_for('resource.edit', name=name, id=item.id))

    return render_template("resource/edit.html",
                           name=name,
                           R=R,
                           item=item,
                           defn=defn,
                           defn_parse=defn_parse,
                           render_column=render_column,
                           defn_parse_raw=defn_parse_raw,
                           get_enum=get_enum)


@resource.route("/<name>/delete/<id>", methods=["GET", "POST"])
@login_required
def delete(name, id):
    try:
        R = get_enum(name)
    except:
        abort(403)

    item = R.query.get_or_404(id)

    if request.method == "POST":
        db.session.delete(item)
        db.session.commit()

    return render_template("resource/delete.html",
                           name=name,
                           R=R,
                           item=item,
                           defn=get_defn(name, scope="display"))


@resource.route("/<name>/new", methods=["GET", "POST"])
@login_required
def new(name):
    try:
        R = get_enum(name)
    except:
        abort(403)

    item = R()
    defn = get_defn(name, scope="display")
    item.title = ""

    if request.method == "POST":
        item = apply_defn_post_data_to_obj(defn, item, is_create=True)
        db.session.add(item)
        db.session.commit()

        flash('Entity successfully created.')
        return redirect(url_for('resource.index', name=name))

    return render_template("resource/new.html",
                           name=name,
                           R=R,
                           item=item,
                           defn=defn,
                           defn_parse=defn_parse,
                           render_column=render_column,
                           defn_parse_raw=defn_parse_raw,
                           get_enum=get_enum)


@resource.route("/<name>/merge/<id>", methods=["GET", "POST"])
@login_required
def merge(name, id):
    if not current_user.has_dev_permissions():
        abort(404)

    try:
        R = get_enum(name)
    except:
        abort(403)

    item = R.query.get_or_404(id)

    if request.method == "POST":
        other = R.query.get(request.form['target'])
        rels = inspect(R).relationships.items()
        for rk, ro in rels:
            here = getattr(item, rk)
            there = getattr(other, rk)

            # This is probably a 1:n relationship, which we can't cover here
            if ro.secondary is None and str(type(ro)) != "<class 'sqlalchemy.orm.relationships.RelationshipProperty'>":
                continue

            here = [*here] # Save current state

            for entry in here:
                print(entry, entry not in there)
                if entry not in there:
                    there.append(entry)
            
            here.clear()

        db.session.delete(item)
        db.session.commit()

        flash('Successfully merged!')
        return redirect(url_for("resource.index", name=name))

    return render_template("resource/merge.html",
                           name=name,
                           R=R,
                           item=item,
                           defn=get_defn(name, scope="display"))


@resource.route("/<name>/-/<id>/rel/<relname>")
def relindex(name, id, relname):
    try:
        R = get_enum(name)
        rel = get_rel(relname)
    except:
        abort(403)

    item = R.query.get_or_404(id)
    q = {get_rel_defn(relname)["per"]: item.id}
    relvals = rel.query.filter_by(**q).all()

    return render_template("resource/rel/index.html",
                           name=name,
                           R=R,
                           relname=relname,
                           rel=rel,
                           relvals=relvals,
                           rel_defn=get_defn(relname, scope="summary"),
                           item=item,
                           defn=get_defn(name, scope="display"))


@resource.route("/<name>/-/<id>/rel/<relname>/new", methods=["GET", "POST"])
@login_required
def relnew(name, id, relname):
    try:
        R = get_enum(name)
        rel = get_rel(relname)
    except:
        abort(403)

    rel_defn = get_defn(relname, scope="display")
    item = R.query.get_or_404(id)
    q = {get_rel_defn(relname)["per"]: item.id}
    relval = rel(**q)

    if request.method == "POST":
        relval = apply_defn_post_data_to_obj(rel_defn, relval, is_create=True)
        print(relval)
        db.session.add(relval)
        db.session.commit()

        flash('Relation successfully created.')
        return redirect(url_for('resource.relindex', name=name, id=id, relname=relname))

    return render_template("resource/rel/new.html",
                           name=name,
                           R=R,
                           relname=relname,
                           rel=rel,
                           relval=relval,
                           rel_defn=rel_defn,
                           item=item,
                           defn=get_defn(name, scope="display"),
                           defn_parse=defn_parse,
                           render_column=render_column,
                           defn_parse_raw=defn_parse_raw,
                           get_enum=get_enum,
                           get_rel_defn=get_rel_defn)


@resource.route("/<name>/-/<id>/rel/<relname>/show/<relid>", methods=["GET", "POST"])
def relshow(name, id, relname):
    pass


@resource.route("/<name>/-/<id>/rel/<relname>/edit/<relid>", methods=["GET", "POST"])
@login_required
def reledit(name, id, relname, relid):
    try:
        R = get_enum(name)
        rel = get_rel(relname)
    except:
        abort(403)

    rel_defn = get_defn(relname, scope="display")
    item = R.query.get_or_404(id)
    q = {get_rel_defn(relname)["per"]: item.id}
    relval = rel.query.get_or_404(relid)

    if request.method == "POST":
        relval = apply_defn_post_data_to_obj(rel_defn, relval)
        db.session.commit()
        flash('Changes committed successfully.')
        return redirect(url_for('resource.reledit', name=name, id=item.id, relname=relname, relid=relval.id))

    return render_template("resource/rel/edit.html",
                           name=name,
                           R=R,
                           relname=relname,
                           rel=rel,
                           relval=relval,
                           rel_defn=rel_defn,
                           item=item,
                           defn=get_defn(name, scope="display"),
                           defn_parse=defn_parse,
                           render_column=render_column,
                           defn_parse_raw=defn_parse_raw,
                           get_enum=get_enum,
                           get_rel_defn=get_rel_defn)


@resource.route("/<name>/-/<id>/rel/<relname>/delete/<relid>", methods=["GET", "POST"])
@login_required
def reldelete(name, id, relname, relid):
    try:
        R = get_enum(name)
        rel = get_rel(relname)
    except:
        abort(403)

    rel_defn = get_defn(relname, scope="display")
    item = R.query.get_or_404(id)
    q = {get_rel_defn(relname)["per"]: item.id}
    relval = rel.query.get_or_404(relid)

    if request.method == "POST":
        db.session.delete(relval)
        db.session.commit()
        return redirect(url_for('resource.relindex', name=name, id=id, relname=relname))
    
    return render_template("resource/rel/confirm_delete.html",
                           name=name,
                           relname=relname,
                           relval=relval,
                           item=item)

def apply_defn_post_data_to_obj(defn, obj, is_create=False):
    for slide in defn['slides']:
        for part in slide['parts']:
            if part["component"] == "standalone":
                cols = [part['single']]
            elif part["component"] == "table":
                cols = part['columns']
            elif part["component"] == "text_view":
                cols = [{
                    'column': part['columns']['epidoc'],

templates/resource/rel/_form.html
{% from "resource/_joint.html" import render_part, render_form_part, rendel with context  %}

{% for slide in rel_defn.slides %}
<section role="doc-part">
    {% if slide.title %}
    <h2>{{ slide.title }}</h2>
    {% endif %}
    
    {% for part in slide.parts %}
    {% set item = relval %}
    {% set name = relname %}
    {{ render_form_part(part, relval, loop) }}
    {% else %}
    {% if slide.auto == "foreach" %}
    {% set autoon = defn_parse_raw(slide.autoon, relval) %}
    {% for autoitem in autoon %}
        {{ render_part(slide.autopart, autoitem, loop) }}
    {% endfor %}
    {% endif %}
    {% endfor %}
</section>
{% endfor %}

templates/resource/rel/confirm_delete.html
{% set title = name %}
{% extends "layouts/application.html" %}

{% block body %}
<h1><a href="{{ url_for('resource.relindex', name=name, id=item.id, relname=relname) }}">{{ relname|camel2human }}</a>: Delete relation</h1>

<form action="" method="post">

    <p>Are you sure you want to delete <strong>{{ relval.display() }}</strong>? This action cannot be undone.</p>

    <button type="submit">Delete</button>&nbsp;
    <a href="{{ url_for('resource.relindex', name=name, id=item.id, relname=relname) }}">Cancel</a>
</form>

{% endblock %}

templates/resource/rel/edit.html
{% set title = name %}
{% extends "layouts/application.html" %}

{% block body %}
<h1><a href="{{ url_for('resource.relindex', name=name, id=item.id, relname=relname) }}">{{ relname|camel2human }}</a>: Edit relation</h1>

<form action="" method="post">

    <div class="toolbar">
        {% if rel_defn.update_action %}
        <button type="submit" class="primary-btn">{{ rel_defn.update_action }}</button>
        {% endif %}
        {% if rel_defn.cancel_action %}
        <a href="{{ url_for('resource.relindex', name=name, id=item.id, relname=relname) }}" role="button">{{ rel_defn.cancel_action }}</a>
        {% endif %}
    </div>

    {% include "resource/rel/_form.html" %}
</form>

{% endblock %}

templates/resource/rel/index.html
{% set title = name %}
{% extends "layouts/application.html" %}

{% block body %}
<h1><a href="{{ url_for('resource.show', name=name, id=item.id) }}">{{ name|camel2human }}: {{ defn_parse(defn.title, item) }}</a></h1>

<h2>{{ relname|camel2human }}</h2>
{% if rel_defn.create_op %}
<div class="toolbar">
    <a href="{{ url_for('resource.relnew', name=name, id=item.id, relname=relname) }}" role="button">{{ rel_defn.create_op }}</a>
</div>
{% endif %}

<table role="table">
    <tbody>
        <tr>
            {% for column in rel_defn.table %}
            <th>{{ column.name }}</th>
            {% endfor %}
            {% if rel_defn.update_op or rel_defn.delete_op %}
            <th></th>
            {% endif %}
        </tr>
        {% for relitem in relvals %}
        <tr>
            {% set primary_loop=loop %}
            {% for column in rel_defn.table %}
            {% if column.linkto and column.linkto == "show" %}
            <td>
                <a href="{{ url_for('resource.relshow', name=name, id=item.id, relname=relname, relid=relitem.id) }}">
                    {{ defn_parse(column.value, relitem, loop=primary_loop) }}
                </a>
            </td>
            {% else %}
            <td>{{ defn_parse(column.value, relitem, loop=primary_loop) }}</td>
            {% endif %}
            {% endfor %}
            {% if rel_defn.update_op or rel_defn.delete_op %}
            <td>
                {% if rel_defn.update_op %}
                <a href="{{ url_for('resource.reledit', name=name, id=item.id, relname=relname, relid=relitem.id) }}" role="button">{{ rel_defn.update_op }}</a>
                {% endif %}
                {% if rel_defn.delete_op %}
                <a href="{{ url_for('resource.reldelete', name=name, id=item.id, relname=relname, relid=relitem.id) }}" role="button">{{ rel_defn.delete_op }}</a>
                {% endif %}
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/resource/rel/new.html
{% set title = name %}
{% extends "layouts/application.html" %}

{% block body %}
<h1><a href="{{ url_for('resource.relindex', name=name, id=item.id, relname=relname) }}">{{ relname|camel2human }}</a>: New item</h1>

<form action="" method="post">

    <div class="toolbar">
        {% if defn.create_action %}
        <button type="submit" class="primary-btn">{{ rel_defn.create_action }}</button>
        {% endif %}
        {% if defn.cancel_action %}
        <a href="{{ url_for('resource.relindex', name=name, id=item.id, relname=relname) }}" role="button">{{ rel_defn.cancel_action }}</a>
        {% endif %}
    </div>

    {% include "resource/rel/_form.html" %}
</form>

{% endblock %}