controllers/info.py
from flask import *
from ..models import db, get_enum

info = Blueprint('info', __name__)

@info.route("/project/concept-and-aim")
def concept_and_aim(): return render_template("info/project/concept_and_aim.html")

@info.route("/project/team")
def team(): return render_template("info/project/team.html")

@info.route("/project/partners")
def partners(): return render_template("info/project/partners.html")

@info.route("/project/events-and-presentations")
def events_and_presentations(): return render_template("info/project/events_and_presentations.html")

@info.route("/project/acknowledgements")
def acknowledgements(): return render_template("info/project/acknowledgements.html")

@info.route("/data")
def data(): return render_template("info/data.html")

@info.route("/bibliography")
def bibliography(): return render_template("info/bibliography.html")

controllers/inscriptions.py
from flask import Blueprint, render_template, make_response, abort, send_file
from ..models import Inscriptions, inscriptions_to_json, inscriptions_to_csv
from flask_security import login_required

import csv, io

inscriptions = Blueprint('inscriptions', __name__)


@inscriptions.route("/map")
def map():
    inscs = Inscriptions.query.all()

    mc = inscriptions_to_json(inscs)

    return render_template("inscriptions/map.html", mc=mc)


@inscriptions.route("/MPL<id>.xml")
def render_xml(id):
    insc = Inscriptions.query.filter_by(id=int(id)).one_or_none()

    if not insc:
        abort(404)

    xml_file = render_template("inscriptions/one.xml", insc=insc)
    response = make_response(xml_file)
    response.headers['Content-Type'] = 'application/xml'

    return response


@login_required
@inscriptions.route("/.unknown/alex.csv")
def alex_export():
    inscs = Inscriptions.query.all()

    csvdata = inscriptions_to_csv(inscs)

    csv_io = io.StringIO()
    csvwriter = csv.writer(csv_io, delimiter=',', quotechar='\"')
    csvwriter.writerows(csvdata)

    mem_io = io.BytesIO()
    mem_io.write(csv_io.getvalue().encode())
    mem_io.seek(0)

    return send_file(mem_io, mimetype='text/csv')

controllers/search.py
from flask import *
from ..models import db, get_enum, Inscriptions, Places, VerseTypes, Publications, People, ObjectDecorationTags, inscription_decoration_tag_assoc, inscriptions_to_json
from ..config import SETTINGS

from sqlalchemy import select

search = Blueprint('search', __name__)


@search.route("/", methods=["GET"])
def index():
    return redirect(url_for('search.basic'))


@search.route("/basic", methods=["GET"])
def basic():
    return render_template("search/basic.html", get_enum=get_enum)


@search.route("/advanced", methods=["GET"])
def advanced():
    return render_template("search/advanced.html", get_enum=get_enum)


@search.route("/basic/do", methods=["GET"])
def basic_do():
    query = Inscriptions.query.distinct()
    places = Places.query
    places_subquery = False

    query, places, places_subquery = _apply_common_filters(
        query, places, places_subquery)

    if places_subquery:
        query = query.filter(Inscriptions.place_id.in_(
            [i[0] for i in places.values(Places.id)]))

    query = _apply_basic_text_filters(query)

    count = query.count()
    results = query.all()
    mc = inscriptions_to_json(results)

    return render_template("search/do.html", results=results, count=count, mc=mc, origin='basic')


@search.route("/advanced/do", methods=["GET"])
def advanced_do():
    query = Inscriptions.query.distinct()
    places = Places.query
    places_subquery = False

    query, places, places_subquery = _apply_common_filters(
        query, places, places_subquery)
    query, places, places_subquery = _apply_advanced_filters(
        query, places, places_subquery)

    if places_subquery:
        query = query.filter(Inscriptions.place_id.in_(
            [i[0] for i in places.values(Places.id)]))

    query = _apply_advanced_text_filters(query)
    query = _apply_advanced_people_filters(query)

    print(query)

    count = query.count()
    results = query.all()
    mc = inscriptions_to_json(results)

    return render_template("search/do.html", results=results, count=count, mc=mc, origin='advanced')


def _apply_common_filters(query, places, places_subquery):
    if 'mappola_id' in request.values.keys() and (mappola_id := request.values.get('mappola_id')) != '':
        query = query.filter(Inscriptions.id == mappola_id)

    if 'province' in request.values.keys() and (province := request.values.get('province')) != '':
        places = places.filter(Places.province_id == province)
        places_subquery = True

    if 'state' in request.values.keys() and (state := request.values.get('state')) != '':
        places = places.filter(Places.modern_state_id == state)
        places_subquery = True

    if 'date_min' in request.values.keys() and (date_min := request.values.get('date_min')) != '':
        query = query.filter(Inscriptions.date_begin >= date_min)

    if 'date_max' in request.values.keys() and (date_max := request.values.get('date_max')) != '':
        query = query.filter(Inscriptions.date_end <= date_max)

    if 'bibliography' in request.values.keys() and (bibliography := request.values.get('bibliography')) != '':
        bibliography = Publications.query.filter(Publications.reference_comment.like(
            f"%{bibliography}%")).union(Publications.query.filter_by(zotero_item_id=bibliography)).all()
        subquery = None

        for bib in bibliography:
            if subquery is None:
                subquery = Inscriptions.publications.contains(bib)
            else:
                subquery = subquery | Inscriptions.publications.contains(bib)

        query = query.filter(subquery)

    if 'verse_type' in request.values.keys() and (verse_types := request.values.getlist('verse_type')) != ['']:
        not_expanded = []
        searched_verse_types = []

        for verse_type in verse_types:
            verse_type = VerseTypes.query.filter_by(id=verse_type).one()
            not_expanded += [verse_type]

        while len(not_expanded):
            vt = not_expanded.pop()

            if vt in searched_verse_types:
                continue

            searched_verse_types.append(vt)
            not_expanded += vt.children

        subquery = None

        for vt in searched_verse_types:
            if subquery is None:
                subquery = Inscriptions.verse_types.contains(vt)
            else:
                subquery = subquery | Inscriptions.verse_types.contains(vt)

        query = query.filter(subquery)

    return query, places, places_subquery


def _apply_basic_text_filters(query):
    if 'text1' in request.values.keys() and (text1 := request.values.get('text1')) != '' and \
            'text2' in request.values.keys() and (text2 := request.values.get('text2')) != '':

        if request.values.get('text_conj', 'AND') == 'OR':
            query = query.filter(Inscriptions.inscription_search_body_cached.ilike(f"%{text1}%")) \
                .union(query.filter(Inscriptions.inscription_search_body_cached.ilike(f"%{text2}%")))
        elif request.values.get('text_conj', 'AND') == 'AND NOT':
            query = query.filter(
                Inscriptions.inscription_search_body_cached.ilike(f"%{text1}%"))
            query = query.filter(
                Inscriptions.inscription_search_body_cached.notlike(f"%{text2}%"))
        else:
            query = query.filter(
                Inscriptions.inscription_search_body_cached.ilike(f"%{text1}%"))
            query = query.filter(
                Inscriptions.inscription_search_body_cached.ilike(f"%{text2}%"))

    elif 'text1' in request.values.keys() and (text1 := request.values.get('text1')) != '':
        query = query.filter(
            Inscriptions.inscription_search_body_cached.ilike(f"%{text1}%"))

    elif 'text2' in request.values.keys() and (text2 := request.values.get('text2')) != '':
        query = query.filter(
            Inscriptions.inscription_search_body_cached.ilike(f"%{text2}%"))

    if 'ft' in request.values.keys() and (ft := request.values.get('ft')) != '':
        query = query.filter(
            Inscriptions.full_text_cached.like(f"%{ft}%"))

    return query


def _apply_advanced_filters(query, places, places_subquery):

    if 'find_place' in request.values.keys() and (find_place := request.values.get('find_place')) != '':
        places = places.filter(Places.id == find_place)
        places_subquery = True

    if 'find_context' in request.values.keys() and (find_context := request.values.get('find_context')) != '':
        query = query.filter(
            Inscriptions.find_comment.ilike(f"%{find_context}%"))

    if 'current_location' in request.values.keys() and (cur_loc := request.values.get('current_location')) != '':
        cur_loc = get_enum('CurrentLocations').query.get(cur_loc)
        query = query.filter(Inscriptions.current_location == cur_loc)

    if 'object_type' in request.values.keys() and (object_type := request.values.get('object_type')) != '':
        object_type = get_enum('ObjectTypes').query.get(object_type)
        query = query.filter(Inscriptions.object_type == object_type)

    if 'object_material' in request.values.keys() and (object_material := request.values.get('object_material')) != '':
        object_material = get_enum(
            'ObjectMaterials').query.get(object_material)
        query = query.filter(Inscriptions.object_material == object_material)

    if 'object_preservation' in request.values.keys() and (object_preservation := request.values.get('object_preservation')) != '':
        object_preservation = get_enum(
            'ObjectPreservationStates').query.get(object_preservation)
        query = query.filter(
            Inscriptions.object_preservation_state == object_preservation)

    if 'object_execution' in request.values.keys() and (object_execution := request.values.get('object_execution')) != '':
        object_execution = get_enum(
            'ObjectExecutionTechniques').query.get(object_execution)
        query = query.filter(
            Inscriptions.object_execution_technique == object_execution)

    if 'religion' in request.values.keys() and (religion := request.values.get('religion')) != '':
        religion = get_enum('Religions').query.get(religion)
        query = query.filter(Inscriptions.religion == religion)

    if 'rhythmisation' in request.values.keys() and (rhythmisation := request.values.get('rhythmisation')) != '':
        rhythmisation = get_enum('VerseTimingTypes').query.get(rhythmisation)
        query = query.filter(Inscriptions.verse_timing_type == rhythmisation)

    if 'translations' in request.values.keys() and (translations := request.values.get('translations')) != '':
        Translations = get_enum('Translations')
        query_on_inscr = Inscriptions.main_translation.ilike(f"%{translations}%")
        query_on_transl = Translations.link_to_published_translation.ilike(f"%{translations}%")

        translations = Translations.query.filter(query_on_transl).all()

        subquery = query_on_inscr

        for translation in translations:
            subquery = subquery | Inscriptions.translations.contains(translation)

        query = query.filter(subquery)

    if 'decoration_tags' in request.values.keys() and (decoration_tags := request.values.getlist('decoration_tags')) != ['']:
        not_expanded = []
        searched_decoration_tags = []

        for decoration_tag in decoration_tags:
            decoration_tag = ObjectDecorationTags.query.filter_by(
                id=decoration_tag).one()
            not_expanded += [decoration_tag]

        while len(not_expanded):
            dt = not_expanded.pop()

            if dt.id in searched_decoration_tags:
                continue

            searched_decoration_tags.append(dt.id)
            not_expanded += dt.children

        query = query.join(ObjectDecorationTags, Inscriptions.decoration_tags).filter(ObjectDecorationTags.id.in_(searched_decoration_tags))

templates/layouts/_head.html
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>{{ title }}</title>

<link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='theme.css') }}">
<script src="{{ url_for('static', filename='main.js') }}" defer></script>

<link rel="stylesheet" href="{{ url_for('static', filename='zotero-integration.css') }}">
<script src="{{ url_for('static', filename='zotero-integration.js') }}" defer></script>
<script src="{{ url_for('static', filename='pleiades-integration.js') }}" defer></script>
<script src="{{ url_for('static', filename='epidoc-converter.js') }}" defer></script>
<script src="https://patrimonium.huma-num.fr/atlas/epidoc-converter/$ausohnum-lib/resources/scripts/teiEditor/ancientTextImportRules.js" defer></script>

<meta name="map.style" content="https://api.maptiler.com/maps/outdoor/style.json?key={{ config['MAPTILER_KEY'] }}" />

<link rel="stylesheet" href="{{ url_for('static', filename='maps/mappola-maps.css') }}" defer>
<script src="{{ url_for('static', filename='maps/mappola-maps.js') }}" defer></script>

<script src="{{ url_for('static', filename='bar.js') }}" defer></script>
<script src="{{ url_for('static', filename='bar-epidoc.js') }}" defer></script>

templates/layouts/_header.html
<header>
    <a href="{{ url_for('index') }}" role="heading">MAPPOLA</a>
    <div class="dropdown">
        <a href="">Project</a>
        <div class="dropdown-area">
            <a href="{{ url_for('info.concept_and_aim') }}">Concept and aim</a>
            <a href="{{ url_for('info.team') }}">Team</a>
            <a href="{{ url_for('info.partners') }}">Partners</a>
            <a href="{{ url_for('info.events_and_presentations') }}">Events and presentations</a>
            <a href="{{ url_for('info.acknowledgements') }}">Acknowledgements</a>
            <a href="mailto:mappola.erc@gmail.com">Contact us</a>
        </div>
    </div>
    <a href="{{ url_for('resource.index', name='Inscriptions') }}">
        Inscriptions
    </a>
    <a href="{{ url_for('search.index') }}">
        Search
    </a>
    <a href="{{ url_for('inscriptions.map') }}">
        Map
    </a>
    <a href="{{ url_for('info.data') }}">
        Data
    </a>

    <div class="dropdown">
        <a href="">Bibliography</a>
        <div class="dropdown-area">
            <a href="{{ url_for('info.bibliography') }}">Abbreviation of corpora</a>
            <a href="https://www.zotero.org/groups/4706630/mappola_library/library" target="_blank">MAPPOLA Library</a>
        </div>
    </div>

    <div role="separator"></div>

    {% if current_user.is_authenticated %}
    <a href="{{ url_for('security.change_password') }}">
        User
        ({{ current_user.full_name }})
    </a>
    <a href="{{ url_for('security.logout') }}">
        Sign Out
    </a>
    {% else %}
    <a href="{{ url_for('security.login') }}">
        Sign In
    </a>
    {% endif %}
</header>

{% with messages = get_flashed_messages() %}
{% if messages %}
<div role="alert">
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}
{% endwith %}

templates/layouts/application.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "layouts/_head.html" %}
</head>
<body>
    {% include "layouts/_header.html" %}

    <main class="container">
        {% block body %}
        {% endblock body %}
    </main>
</body>
</html>