controllers/search.py
from flask import *
from ..models import db, get_enum, Inscriptions, Places, VerseTypes, Publications, People, ObjectDecorationTags, inscription_decoration_tag_assoc, inscriptions_to_json
from ..config import SETTINGS

from sqlalchemy import select

search = Blueprint('search', __name__)


@search.route("/", methods=["GET"])
def index():
    return redirect(url_for('search.basic'))


@search.route("/basic", methods=["GET"])
def basic():
    return render_template("search/basic.html", get_enum=get_enum)


@search.route("/advanced", methods=["GET"])
def advanced():
    return render_template("search/advanced.html", get_enum=get_enum)


@search.route("/basic/do", methods=["GET"])
def basic_do():
    query = Inscriptions.query.distinct()
    places = Places.query
    places_subquery = False

    query, places, places_subquery = _apply_common_filters(
        query, places, places_subquery)

    if places_subquery:
        query = query.filter(Inscriptions.place_id.in_(
            [i[0] for i in places.values(Places.id)]))

    query = _apply_basic_text_filters(query)

    count = query.count()
    results = query.all()
    mc = inscriptions_to_json(results)

    return render_template("search/do.html", results=results, count=count, mc=mc, origin='basic')


@search.route("/advanced/do", methods=["GET"])
def advanced_do():
    query = Inscriptions.query.distinct()
    places = Places.query
    places_subquery = False

    query, places, places_subquery = _apply_common_filters(
        query, places, places_subquery)
    query, places, places_subquery = _apply_advanced_filters(
        query, places, places_subquery)

    if places_subquery:
        query = query.filter(Inscriptions.place_id.in_(
            [i[0] for i in places.values(Places.id)]))

    query = _apply_advanced_text_filters(query)
    query = _apply_advanced_people_filters(query)

    print(query)

    count = query.count()
    results = query.all()
    mc = inscriptions_to_json(results)

    return render_template("search/do.html", results=results, count=count, mc=mc, origin='advanced')


def _apply_common_filters(query, places, places_subquery):
    if 'mappola_id' in request.values.keys() and (mappola_id := request.values.get('mappola_id')) != '':
        query = query.filter(Inscriptions.id == mappola_id)

    if 'province' in request.values.keys() and (province := request.values.get('province')) != '':
        places = places.filter(Places.province_id == province)
        places_subquery = True

    if 'state' in request.values.keys() and (state := request.values.get('state')) != '':
        places = places.filter(Places.modern_state_id == state)
        places_subquery = True

    if 'date_min' in request.values.keys() and (date_min := request.values.get('date_min')) != '':
        query = query.filter(Inscriptions.date_begin >= date_min)

    if 'date_max' in request.values.keys() and (date_max := request.values.get('date_max')) != '':
        query = query.filter(Inscriptions.date_end <= date_max)

    if 'bibliography' in request.values.keys() and (bibliography := request.values.get('bibliography')) != '':
        bibliography = Publications.query.filter(Publications.reference_comment.like(
            f"%{bibliography}%")).union(Publications.query.filter_by(zotero_item_id=bibliography)).all()
        subquery = None

        for bib in bibliography:
            if subquery is None:
                subquery = Inscriptions.publications.contains(bib)
            else:
                subquery = subquery | Inscriptions.publications.contains(bib)

        query = query.filter(subquery)

    if 'verse_type' in request.values.keys() and (verse_types := request.values.getlist('verse_type')) != ['']:
        not_expanded = []
        searched_verse_types = []

        for verse_type in verse_types:
            verse_type = VerseTypes.query.filter_by(id=verse_type).one()
            not_expanded += [verse_type]

        while len(not_expanded):
            vt = not_expanded.pop()

            if vt in searched_verse_types:
                continue

            searched_verse_types.append(vt)
            not_expanded += vt.children

        subquery = None

        for vt in searched_verse_types:
            if subquery is None:
                subquery = Inscriptions.verse_types.contains(vt)
            else:
                subquery = subquery | Inscriptions.verse_types.contains(vt)

        query = query.filter(subquery)

    return query, places, places_subquery


def _apply_basic_text_filters(query):
    if 'text1' in request.values.keys() and (text1 := request.values.get('text1')) != '' and \
            'text2' in request.values.keys() and (text2 := request.values.get('text2')) != '':

        if request.values.get('text_conj', 'AND') == 'OR':
            query = query.filter(Inscriptions.inscription_search_body_cached.ilike(f"%{text1}%")) \
                .union(query.filter(Inscriptions.inscription_search_body_cached.ilike(f"%{text2}%")))
        elif request.values.get('text_conj', 'AND') == 'AND NOT':
            query = query.filter(
                Inscriptions.inscription_search_body_cached.ilike(f"%{text1}%"))
            query = query.filter(
                Inscriptions.inscription_search_body_cached.notlike(f"%{text2}%"))
        else:
            query = query.filter(
                Inscriptions.inscription_search_body_cached.ilike(f"%{text1}%"))
            query = query.filter(
                Inscriptions.inscription_search_body_cached.ilike(f"%{text2}%"))

    elif 'text1' in request.values.keys() and (text1 := request.values.get('text1')) != '':
        query = query.filter(
            Inscriptions.inscription_search_body_cached.ilike(f"%{text1}%"))

    elif 'text2' in request.values.keys() and (text2 := request.values.get('text2')) != '':
        query = query.filter(
            Inscriptions.inscription_search_body_cached.ilike(f"%{text2}%"))

    if 'ft' in request.values.keys() and (ft := request.values.get('ft')) != '':
        query = query.filter(
            Inscriptions.full_text_cached.like(f"%{ft}%"))

    return query


def _apply_advanced_filters(query, places, places_subquery):

    if 'find_place' in request.values.keys() and (find_place := request.values.get('find_place')) != '':
        places = places.filter(Places.id == find_place)
        places_subquery = True

    if 'find_context' in request.values.keys() and (find_context := request.values.get('find_context')) != '':
        query = query.filter(
            Inscriptions.find_comment.ilike(f"%{find_context}%"))

    if 'current_location' in request.values.keys() and (cur_loc := request.values.get('current_location')) != '':
        cur_loc = get_enum('CurrentLocations').query.get(cur_loc)
        query = query.filter(Inscriptions.current_location == cur_loc)

    if 'object_type' in request.values.keys() and (object_type := request.values.get('object_type')) != '':
        object_type = get_enum('ObjectTypes').query.get(object_type)
        query = query.filter(Inscriptions.object_type == object_type)

    if 'object_material' in request.values.keys() and (object_material := request.values.get('object_material')) != '':
        object_material = get_enum(
            'ObjectMaterials').query.get(object_material)
        query = query.filter(Inscriptions.object_material == object_material)

    if 'object_preservation' in request.values.keys() and (object_preservation := request.values.get('object_preservation')) != '':
        object_preservation = get_enum(
            'ObjectPreservationStates').query.get(object_preservation)
        query = query.filter(
            Inscriptions.object_preservation_state == object_preservation)

    if 'object_execution' in request.values.keys() and (object_execution := request.values.get('object_execution')) != '':
        object_execution = get_enum(
            'ObjectExecutionTechniques').query.get(object_execution)
        query = query.filter(
            Inscriptions.object_execution_technique == object_execution)

    if 'religion' in request.values.keys() and (religion := request.values.get('religion')) != '':
        religion = get_enum('Religions').query.get(religion)
        query = query.filter(Inscriptions.religion == religion)

    if 'rhythmisation' in request.values.keys() and (rhythmisation := request.values.get('rhythmisation')) != '':
        rhythmisation = get_enum('VerseTimingTypes').query.get(rhythmisation)
        query = query.filter(Inscriptions.verse_timing_type == rhythmisation)

    if 'translations' in request.values.keys() and (translations := request.values.get('translations')) != '':
        Translations = get_enum('Translations')
        query_on_inscr = Inscriptions.main_translation.ilike(f"%{translations}%")
        query_on_transl = Translations.link_to_published_translation.ilike(f"%{translations}%")

        translations = Translations.query.filter(query_on_transl).all()

        subquery = query_on_inscr

        for translation in translations:
            subquery = subquery | Inscriptions.translations.contains(translation)

        query = query.filter(subquery)

    if 'decoration_tags' in request.values.keys() and (decoration_tags := request.values.getlist('decoration_tags')) != ['']:
        not_expanded = []
        searched_decoration_tags = []

        for decoration_tag in decoration_tags:
            decoration_tag = ObjectDecorationTags.query.filter_by(
                id=decoration_tag).one()
            not_expanded += [decoration_tag]

        while len(not_expanded):
            dt = not_expanded.pop()

            if dt.id in searched_decoration_tags:
                continue

            searched_decoration_tags.append(dt.id)
            not_expanded += dt.children

        query = query.join(ObjectDecorationTags, Inscriptions.decoration_tags).filter(ObjectDecorationTags.id.in_(searched_decoration_tags))

templates/search/basic.html
{% set title = name %}
{% extends "layouts/application.html" %}

{% block body %}
<h1>Search</h1>
<p><a href="{{ url_for('search.advanced') }}">Prefer advanced search?</a></p>

<form action="{{ url_for('search.basic_do') }}" method="GET">
    <div class="toolbar">
        <button type="submit" class="primary-btn">Search</button>
        <button type="reset">Clear</button>
    </div>
    <table role="table">
        <tbody>
            <tr>
                <th>Mappola No.</th>
                <td>
                    MPL <input id="q-mappola_id" name="mappola_id" class="no-block">
                </td>
            </tr>
            <tr>
                <th>province</th>
                <td>
                    <select id="q-province" name="province">
                        <option selected></option>
                        {% for e in get_enum('Provinces').query.order_by("title").all() %}
                        <option value="{{ e.id }}">
                            {{ e.title }}
                        </option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <th>country</th>
                <td>
                    <select id="q-state" name="state">
                        <option selected></option>
                        {% for e in get_enum('ModernStates').query.order_by("title").all() %}
                        <option value="{{ e.id }}">
                            {{ e.title }}
                        </option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <th>verse type</th>
                <td>
                    <select id="q-verse_type" name="verse_type">
                        <option selected></option>
                        {% for e in get_enum('VerseTypes').query.order_by("title").all() %}
                        <option value="{{ e.id }}">
                            {{ e.title }}
                        </option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <th>date</th>
                <td>
                    from <input id="q-date_from" type="number" class="no-block" name="date_min">
                    to <input id="q-date_to" type="number" class="no-block" name="date_max">
                </td>
            </tr>
            <tr>
                <th>bibliography</th>
                <td>
                    <input id="q-bibliography" name="bibliography">
                </td>
            </tr>
            <tr>
                <th>inscription text</th>
                <td>
                    <input id="q-text-1" name="text1">
                    <select class="no-block" id="q-text-conj" name="text_conj">
                        <option>AND</option>
                        <option>OR</option>
                        <option>AND NOT</option>
                    </select>
                    <input id="q-text-2" name="text2">
                </td>
            </tr>
            <tr>
                <th>full text search</th>
                <td>
                    <input id="q-fulltext" name="ft">
                </td>
            </tr>
        </tbody>
    </table>
</form>
{% endblock %}

templates/search/basic_do.html
{% set title = name %}
{% extends "layouts/application.html" %}

{% block body %}
<h1>Search</h1>
<p><a href="{{ url_for('search.basic') }}">New search</a></p>

<div id="the-map"></div>
<div data-json aria-hidden="true">{{ mc|tojson }}</div>

<p>You got <strong>{{ count }} result(s)</strong>. {% if count > 100 %}There are more than 100 results, please refine your search to be more specific.{% endif %}</p>

<ul>
    {% for insc in results %}
    <li><a href="{{ url_for('resource.show', name='Inscriptions', id=insc.id) }}">{{ insc.title }}</a></li>
    {% endfor %}
</ul>

<script>
window.onload = function() {
    // A JavaScript array with the search results
    var results = JSON.parse(document.querySelector("[data-json]").innerText);

    // You can set in initialization...
    var map = new Mappola.SearchResultMap({
      // Mandatory: the container DIV
      parent: document.getElementById('the-map'), 

      // Optional: search results to show initially
      results: results
    });
}
</script>
{% endblock %}

templates/search/do.html
{% set title = name %}
{% extends "layouts/application.html" %}

{% block body %}
<h1>Search</h1>
<p><a href="{{ url_for('search.basic' if origin == 'basic' else 'search.advanced') }}">New search</a></p>

{% if count >= 1 %}
<div id="the-map"></div>
<div data-json aria-hidden="true">{{ mc|tojson }}</div>
{% endif %}

<p>You got <strong>{{ count }} result(s)</strong>. {% if count > 100 %}There are more than 100 results, please refine your search to be more specific.{% endif %}</p>

<ul>
    {% for insc in results %}
    <li><a href="{{ url_for('resource.show', name='Inscriptions', id=insc.id) }}">{{ insc.title }}</a></li>
    {% endfor %}
</ul>

{% if count >= 1 %}
<script>
window.onload = function() {
    // A JavaScript array with the search results
    var results = JSON.parse(document.querySelector("[data-json]").innerText);

    // You can set in initialization...
    var map = new Mappola.SearchResultMap({
      // Mandatory: the container DIV
      parent: document.getElementById('the-map'), 

      // Optional: search results to show initially
      results: results
    });
}
</script>
{% endif %}
{% endblock %}